### ISSUE TITLE
应该按日期保存？而且要考虑单个日志文件大小吧？

### ISSUE THREAD

**Issue by he426100** [easy-framework/easy-log#1]
以下是仿写thinkphp的log
`
$destination = ROOT_PATH . 'temp/log/' . date('Ym') . '/' . $name . date('d') . '.log';
$path = dirname($destination);
!is_dir($path) && mkdir($path, 0755, true);
//检测日志文件大小，超过配置大小则备份日志文件重新生成
if (is_file($destination) && floor(self::$config['file_size']) <= filesize($destination)) {
       rename($destination, dirname($destination) . '/' . gmtime() . '-' . basename($destination));
}
`

**Comment by TIGERB** [comment]
嗯嗯，不错，我搞搞～

好的建议 没考虑到～

**Comment by TIGERB** [comment]
已加～
